repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      # - id: name-tests-test
      #   args: ["--django"]
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.6.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.0
    hooks:
      - id: check-github-workflows
