version: "3.9"
services:
  frontend-ts:
    container_name: frontend
    build:
      context: frontend-ts
      target: frontend-ts
    ports:
      - "3000:3000"
    # Watch and react to changes in local...
    volumes:
      #  frontend-ts/src directory
      - type: bind
        source: ./frontend-ts/src
        target: /frontend-ts/src
      #  data directory
      - type: bind
        source: ./data
        target: /data

  backend-py:
    container_name: backend-py
    build:
      context: backend-py
      target: backend-py
    ports:
      - "5100:5100"
    # Watch and react to changes in local...
    volumes:
      #  backend-ts/src directory
      - type: bind
        source: ./backend-py/src
        target: /backend-py/src
      #  data directory
      - type: bind
        source: ./data
        target: /data

  backend-ts:
    container_name: backend-ts
    build:
      context: backend-ts
      target: backend-ts

    ports:
      - "5200:5200"
    # Watch and react to changes in local...
    volumes:
      #  backend-ts/src directory
      - type: bind
        source: ./backend-ts/src
        target: /backend-ts/src
      #  data directory
      - type: bind
        source: ./data
        target: /data
