version: "3.9"
services:
  # backend-py:
  #   build:
  #     context: .
  #     target: backend-py
  # backend-ts:
  #   build:
  #     context: .
  #     target: backend-ts
  frontend-ts:
    build:
      context: .
      target: frontend-ts
    ports:
      - "3000:3000"
    volumes:
      - /frontend-ts:/frontend-ts
