version: "2"
authtoken: <your auth token here>

tunnels:
  acme-frontend:
    proto: http
    # hostname: <Optional: Put static hostname for frontend here>
    # Make sure this addr matches REACT_APP_PORT in .env
    addr: 3000
  acme-backend-py:
    proto: http
    # hostname: <Optional: Put static hostname for python backend here>
    # Make sure this addr matches FLASK_RUN_PORT in .env
    addr: 5100
  acme-backend-ts:
    proto: http
    # hostname: <Optional: Put static hostname for TS backend here>
    # Make sure this addr matches EXPRESS_LISTEN_PORT in .env
    addr: 5200
