name: "Setup Test Database"
description: "Build and serve a local testing database"

runs:
  using: "composite"
  steps:
    - name: Build Test Database
      run: docker-compose build test-database
      shell: bash

    - name: Serve Test Database
      run: docker-compose up test-database
      shell: bash
