name: "Setup Test Database"
description: "Build and serve a local testing database"

runs:
  using: "composite"
  steps:

    - name: Build Test Database
      run: docker-compose --env-file .env.sample build test-database
      shell: bash

    - name: Serve Test Database
      run: docker-compose --env-file .env.sample up test-database
      shell: bash
