name: backend-py
on:
  pull_request:
    paths:
      - ".github/actions/setup-test"
      - ".github/workflows/backend-py.yml"
      - "backend-py/*"
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: "./.github/actions/setup-test"

      - name: Install Python Dependecies
        working-directory: backend-py
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: backend-py
        run: pytest
