name: backend-ts
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: "./.github/actions/setup-node"
        with:
          project_directory: backend-ts
      - uses: "./.github/actions/setup-test"

      - name: Run Tests
        working-directory: backend-ts
        run: npm run test:ci
