name: backend-py
on:
  pull_request:
    paths:
      - ".github/actions/setup-test"
      - ".github/workflows/backend-py.yml"
      - "backend-py/*"
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: "./.github/actions/setup-test"

      - name: Install Python Dependecies
        working-directory: backend-py
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: backend-py
        run: pytest

  docker:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test image starts up
        run: |
          cd backend-py
          docker build -t backend-py:latest .
          container_id=$(docker run -p 5100:5100 -d backend-py:latest)
          sleep 5
          curl --request POST http://0.0.0.0:5100  2>&1
          [ $? == 0 ] && exit 0 || docker logs $container_id && exit 1
